name: Update Landscape from LFX
description: Update the given landscape from LFx
inputs:
  project_processing:
    description: "Indicate for project processing, if they should be 'rebuild' or 'sync' ( or 'skip' to not build projects )"
    default: "sync"
runs:
  using: composite
  steps:
    - name: Checkout landscape
      uses: actions/checkout@v4
      with:
        token: ${{ env.token }}
        repository: ${{ env.repository }}
        ref: ${{ env.ref }}
        path: landscape
    - name: Checkout landscape-tools
      uses: actions/checkout@v4
      with:
        token: ${{ env.token }}
        repository: jmertic/landscape-tools
        path: landscape-tools
        ref: include-projects
    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install poetry
      uses: abatilo/actions-poetry@v2
    - name: Install dependencies
      shell: bash
      working-directory: ./landscape-tools
      run: poetry install
    - name: Build members from LFX
      working-directory: ./landscape-tools
      shell: bash
      run: poetry run landscape -v build_members -c ../landscape/config.yml
    - name: Rebuild projects from LFX and other sources
      if: ${{ inputs.project_processing == 'rebuild' }}
      working-directory: ./landscape-tools
      shell: bash
      run: poetry run landscape -v build_projects -c ../landscape/config.yml
    - name: Sync projects from LFX and other sources
      if: ${{ inputs.project_processing == 'sync' }}
      working-directory: ./landscape-tools
      shell: bash
      run: poetry run landscape -v sync_projects -c ../landscape/config.yml
    - name: Save missing.csv file
      uses: actions/upload-artifact@v4
      with:
        name: missing-members 
        path: ./landscape/missing.csv
    - name: Checkout landscapeapp
      uses: actions/checkout@v4
      with:
        repository: cncf/landscapeapp
        path: landscapeapp
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: Cleanup YAML files
      working-directory: ./landscapeapp
      shell: bash
      run: |
        node tools/removePuppeteer
        npm install
        PROJECT_PATH=../landscape node tools/removeQuotes
        PROJECT_PATH=../landscape node tools/pruneExtraEntries
    - name: Get current date
      id: date
      uses: Kaven-Universe/github-action-current-date-time@v1
      with:
        format: "YYYY-MM-DD"
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ env.token }}
        branch-suffix: timestamp
        path: ./landscape
        title: "Update Landscape from LFX ${{ steps.date.outputs.time }}"
        labels: automated-build
        commit-message: Update Landscape from LFX

